

async function run() {
	try {

	}
	catch (err) {
		console.error(err);
	}
}

run().catch(console.error);